quotes/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^quotes/', include('webapp.urls', namespace='webapp')),
    url(r'^$', RedirectView.as_view(url='quotes'), name='home'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('allauth.urls')),
)

webapp/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', views.ViewQuote.as_view(), name='view_single'),
    url(r'^(?P<pk>\d+)/delete/$', views.DeleteQuote.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/edit/$', views.EditQuote.as_view(), name='edit'),
    url(r'^add/$', views.AddQuote.as_view(), name='add'),
    url(r'^$', views.QuoteList.as_view(), name='view_all'),
)

webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from guardian.shortcuts import assign_perm


class Quote(models.Model):
    quote_text = models.TextField()
    quote_source = models.CharField(max_length=100)
    added_on = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, default=1)

    class Meta:
        ordering = ['-added_on']

    def __unicode__(self):
        return u'{} quote by {}'.format(self.quote_source, self.added_by.username)


@receiver(post_save, sender=Quote)
def set_perms(sender, **kwargs):
    if kwargs['created']:
        quote = kwargs['instance']
        assign_perm('change_quote', quote.added_by, quote)
        assign_perm('delete_quote', quote.added_by, quote)

webapp/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse
from guardian.mixins import PermissionRequiredMixin, LoginRequiredMixin
from .models import Quote


class AddQuote(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Quote
    fields = ['quote_text', 'quote_source']
    template_name = 'edit.html'
    success_message = "Your quote has been added!"

    def get_context_data(self, **kwargs):
        ctx = super(AddQuote, self).get_context_data(**kwargs)
        ctx['mode'] = 'Add a new'
        return ctx

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        return super(AddQuote, self).form_valid(form)

    def get_success_url(self):
        return reverse('webapp:view_single', args=(self.object.pk,))


class EditQuote(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'edit.html'
    model = Quote
    fields = ['quote_text', 'quote_source']
    success_message = "Quote has been changed!"
    permission_required = 'auth.change_quote'

    def get_context_data(self, **kwargs):
        ctx = super(EditQuote, self).get_context_data(**kwargs)
        ctx['mode'] = 'Editing'
        ctx['number'] = '#{}'.format(ctx['quote'].pk)
        return ctx

    def get_success_url(self):
        return reverse('webapp:view_single', args=(self.object.pk,))


class ViewQuote(DetailView):
    model = Quote
    template_name = 'quote.html'


class QuoteList(ListView):
    model = Quote
    template_name = 'index.html'
    context_object_name = 'quotes'
    paginate_by = 4


class DeleteQuote(SuccessMessageMixin, LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Quote
    success_url = '/'
    success_message = "Quote has been deleted!"
    permission_required = 'auth.delete_quote'

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    {% block extrahead %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/css/bootstrap.min.css">
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Forum'>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/js/bootstrap.min.js"></script>
    <script src="{% static "js/modal.js" %}"></script>
    {% endblock %}
</head>
<body>
{% include "logout_modal.html" %}
<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Quotes</a>
  </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
        {% block nav %}
        {% endblock %}
    </ul>
    <ul class="nav navbar-nav navbar-right navbar-collapse">
        {% if user.is_authenticated %}
        <li class="dropdown">
            <button type="button" class="dropdown-toggle btn navbar-btn btn-default" data-toggle="dropdown">Logged in as {{ user.username }}<b class="caret"></b></button>
            <ul class="dropdown-menu">
                {% if user.is_staff %}
                    <li><a href="/admin/">Admin</a></li>
                {% endif %}
                <li><a href="{% url "account_logout" %}" onclick="showLogoutModal(); return false;">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li><a href="{% url "account_login" %}">Sign in</a></li>
        <li><a href="{% url "account_signup" %}">Register</a></li>
        {% endif %}
    </ul>
 </div>
</nav>

<div class="container">
    {% load bootstrap3 %}
    {% bootstrap_messages %}
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

webapp/templates/delete.html
{% load staticfiles %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="{% static "js/modal.js" %}"></script>
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block body %}
<div class="modal fade" id="deleteModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Quote</h4>
      </div>
      <div class="modal-body">
        <p>Delete this quote?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" onclick="deleteQuote('{% url "webapp:delete" quote.pk %}', '{{ csrf_token }}');">Yes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

webapp/templates/delete_modal.html
{% block body %}
<div class="modal fade" id="deleteModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Quote</h4>
      </div>
      <div class="modal-body">
        <p>Delete this quote?</p>
      </div>
      <div class="modal-footer">
        <form method="post" action="{% url "webapp:delete" quote.pk %}">
          {% csrf_token %}
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Yes</button>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

webapp/templates/edit.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}{{mode}} quote{% endblock %}
{% block body %}
    <h1 class="page-header">{{mode}} quote {{number}}</h1>
    <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Submit" "submit" %}
        {% if number %}
            <a href="{% url "webapp:view_single" form.instance.pk %}" class="btn btn-default">Cancel</a>
        {% else %}
            <a href="/" class="btn btn-default">Cancel</a>
        {% endif %}
    </form>
{% endblock %}

webapp/templates/index.html
{% extends "base.html" %}
{% block title %}Quotes{% endblock %}
{% block nav %}
{% if user.is_authenticated %}
    <li><a href="{% url "webapp:add" %}">Add new</a></li>
{% endif %}
{% endblock %}
{% block body %}
    {% for quote in quotes %}
        <blockquote class="jumbotron">
        <div class="quote">
            <div class="quote-mark">&#8220;</div>
            <p>{{ quote.quote_text }}</p>
            <div class="quote-mark quote-end">&#8221;</div>
        </div>
        <span class="quote-date"><a href="{% url "webapp:view_single" quote.pk %}">Added on: {{ quote.added_on.date }}</a></span>
        <small><cite>{{ quote.quote_source }}</cite></small>
    </blockquote>
    {% empty %}
        <p>Nothing to see here, would you like to <a href="{% url 'webapp:add' %}">add one</a>?</p>
    {% endfor %}
    {% if is_paginated %}
    <ul class="pager">
        {% if page_obj.has_previous %}
            {% if page_obj.previous_page_number == 1 %}
            <li><a href="{% url "webapp:view_all" %}">Previous</a></li>
            {% else %}
            <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}

webapp/templates/logout_modal.html
{% block body %}
<div class="modal fade" id="logoutModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Logout</h4>
      </div>
      <div class="modal-body">
        <p>Do you want to logout?</p>
      </div>
      <div class="modal-footer">
        <form method="post" action="{% url "account_logout" %}">
          {% csrf_token %}
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Yes</button>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

webapp/templates/new.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Add new quote{% endblock %}
{% block body %}
    <h1 class="page-header">Add new quote</h1>
    <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Submit" "submit" %}
    </form>
{% endblock %}

webapp/templates/quote.html
{% extends "base.html" %}
{% load guardian_tags %}
{% block title %}Quote #{{quote.pk}}{% endblock %}
{% block nav %}
{% if user.is_authenticated %}
  {% get_obj_perms user for quote as "quote_perms" %}
  {% if 'delete_quote' in quote_perms %}
    <li><a href="{% url "webapp:delete" quote.pk %}" onclick="showDeleteModal(); return false;" id="deleteLink">Delete</a></li>
  {% endif %}
  {% if 'change_quote' in quote_perms %}
    <li><a href="{% url "webapp:edit" quote.pk %}" id="editLink">Edit</a></li>
  {% endif %}
{% endif %}
{% endblock %}
{% block body %}
    {% include "delete_modal.html" %}
    <h1>Quote #{{quote.pk}}</h1>
        <blockquote class="jumbotron">
            <div class="quote">
                <div class="quote-mark">&#8220;</div>
                <p>{{ quote.quote_text }}</p>
                <div class="quote-mark quote-end">&#8221;</div>
            </div>
           <span class="quote-date">Added on: {{quote.added_on}}</span>
           <small><cite>{{ quote.quote_source }}</cite></small>
       </blockquote>
{% endblock %}